// Optimized icons.ts - only exports actually used icons

export { Activity } from 'lucide-react';
export { AlertCircle } from 'lucide-react';
export { AlertTriangle } from 'lucide-react';
export { Archive } from 'lucide-react';
export { ArrowDownRight } from 'lucide-react';
export { ArrowLeft } from 'lucide-react';
export { ArrowRight } from 'lucide-react';
export { ArrowUpDown } from 'lucide-react';
export { ArrowUpRight } from 'lucide-react';
export { Award } from 'lucide-react';
export { BarChart3 } from 'lucide-react';
export { Bell } from 'lucide-react';
export { Bold } from 'lucide-react';
export { BookOpen } from 'lucide-react';
export { Briefcase } from 'lucide-react';
export { Building } from 'lucide-react';
export { Building2 } from 'lucide-react';
export { Calculator } from 'lucide-react';
export { Calendar } from 'lucide-react';
export { CalendarDays } from 'lucide-react';
export { Camera } from 'lucide-react';
export { Check } from 'lucide-react';
export { CheckCircle } from 'lucide-react';
export { ChevronDown } from 'lucide-react';
export { ChevronLeft } from 'lucide-react';
export { ChevronRight } from 'lucide-react';
export { ChevronUp } from 'lucide-react';
export { ChevronsLeft } from 'lucide-react';
export { ChevronsRight } from 'lucide-react';
export { Circle } from 'lucide-react';
export { Clock } from 'lucide-react';
export { CloudRain } from 'lucide-react';
export { Code } from 'lucide-react';
export { Coffee } from 'lucide-react';
export { Copy } from 'lucide-react';
export { CreditCard } from 'lucide-react';
export { Crown } from 'lucide-react';
export { DollarSign } from 'lucide-react';
export { Download } from 'lucide-react';
export { Droplets } from 'lucide-react';
export { Edit } from 'lucide-react';
export { ExternalLink } from 'lucide-react';
export { Eye } from 'lucide-react';
export { EyeOff } from 'lucide-react';
export { Factory } from 'lucide-react';
export { FileCheck } from 'lucide-react';
export { FileStack } from 'lucide-react';
export { FileText } from 'lucide-react';
export { Filter } from 'lucide-react';
export { Flame } from 'lucide-react';
export { Gauge } from 'lucide-react';
export { Globe } from 'lucide-react';
export { Grid3X3 } from 'lucide-react';
export { HardDrive } from 'lucide-react';
export { Hash } from 'lucide-react';
export { Heading1 } from 'lucide-react';
export { Heading2 } from 'lucide-react';
export { Heading3 } from 'lucide-react';
export { Heart } from 'lucide-react';
export { Image } from 'lucide-react';
export { Info } from 'lucide-react';
export { Italic } from 'lucide-react';
export { Key } from 'lucide-react';
export { Layers } from 'lucide-react';
export { LayoutDashboard } from 'lucide-react';
export { Leaf } from 'lucide-react';
export { Lightbulb } from 'lucide-react';
export { LineChart } from 'lucide-react';
export { Link } from 'lucide-react';
export { List } from 'lucide-react';
export { ListOrdered } from 'lucide-react';
export { Loader2 } from 'lucide-react';
export { Lock } from 'lucide-react';
export { LogOut } from 'lucide-react';
export { Mail } from 'lucide-react';
export { MapPin } from 'lucide-react';
export { Maximize } from 'lucide-react';
export { Maximize2 } from 'lucide-react';
export { Menu } from 'lucide-react';
export { MessageSquare } from 'lucide-react';
export { Minimize } from 'lucide-react';
export { Minus } from 'lucide-react';
export { Monitor } from 'lucide-react';
export { MoreHorizontal } from 'lucide-react';
export { MoreVertical } from 'lucide-react';
export { Mountain } from 'lucide-react';
export { Package } from 'lucide-react';
export { Palette } from 'lucide-react';
export { Paperclip } from 'lucide-react';
export { Pause } from 'lucide-react';
export { Percent } from 'lucide-react';
export { Phone } from 'lucide-react';
export { PieChart } from 'lucide-react';
export { Plane } from 'lucide-react';
export { Play } from 'lucide-react';
export { Plus } from 'lucide-react';
export { Quote } from 'lucide-react';
export { Recycle } from 'lucide-react';
export { Redo } from 'lucide-react';
export { RefreshCw } from 'lucide-react';
export { Rocket } from 'lucide-react';
export { RotateCw } from 'lucide-react';
export { Save } from 'lucide-react';
export { Scale } from 'lucide-react';
export { Search } from 'lucide-react';
export { Send } from 'lucide-react';
export { Settings } from 'lucide-react';
export { Share } from 'lucide-react';
export { Share2 } from 'lucide-react';
export { Shield } from 'lucide-react';
export { Ship } from 'lucide-react';
export { ShoppingCart } from 'lucide-react';
export { SkipBack } from 'lucide-react';
export { SkipForward } from 'lucide-react';
export { SlidersHorizontal } from 'lucide-react';
export { Smartphone } from 'lucide-react';
export { Sparkles } from 'lucide-react';
export { Sprout } from 'lucide-react';
export { Star } from 'lucide-react';
export { StarOff } from 'lucide-react';
export { Sun } from 'lucide-react';
export { Tablet } from 'lucide-react';
export { Tag } from 'lucide-react';
export { Target } from 'lucide-react';
export { Thermometer } from 'lucide-react';
export { Trash2 } from 'lucide-react';
export { TreePine } from 'lucide-react';
export { TrendingDown } from 'lucide-react';
export { TrendingUp } from 'lucide-react';
export { Truck } from 'lucide-react';
export { Undo } from 'lucide-react';
export { Upload } from 'lucide-react';
export { User } from 'lucide-react';
export { UserCheck } from 'lucide-react';
export { Users } from 'lucide-react';
export { Video } from 'lucide-react';
export { Volume2 } from 'lucide-react';
export { VolumeX } from 'lucide-react';
export { Wind } from 'lucide-react';
export { X } from 'lucide-react';
export { XCircle } from 'lucide-react';
export { Zap } from 'lucide-react';
export { ZoomIn } from 'lucide-react';
export { ZoomOut } from 'lucide-react';

// Icon aliases for compatibility
export { Search as SearchIcon } from 'lucide-react';
export { ArrowUp as SortAsc } from 'lucide-react';
export { ArrowDown as SortDesc } from 'lucide-react';
export { ArrowUp as SortAscIcon } from 'lucide-react';
export { ArrowDown as SortDescIcon } from 'lucide-react';
export { Grid3X3 as GridIcon } from 'lucide-react';
export { List as ListIcon } from 'lucide-react';
export { Loader2 as LoaderIcon } from 'lucide-react';
export { Calendar as CalendarIcon } from 'lucide-react';
export { Filter as FilterIcon } from 'lucide-react';
export { X as XIcon } from 'lucide-react';

export type { LucideIcon } from 'lucide-react';
